heading: Muotka 2025 - TrailTreader

defaults:
  walkingSpeed: 3
  numberOfZeroDays: 1
  tileLayer: "NLS Topographic map"
  availableTileLayers:
    - "Esri World Imagery"
    - "OpenTopoMap"
    - "OpenStreetMap"
    - "NLS Topographic map"
    #- "NLS Ortophoto"
  trip:
    color: 'black'
    opacity: 0.7
    weight: 7
    endIcon: ../assets/images/bonfire-outline.svg
    mealPlan:
      breakfast: true
      lunch: true
      dinner: true
      snacks: true
  alternatives:
    color: 'blue'
    opacity: 0.7
    weight: 5
    dashArray: '7, 7'
    endIcon: ../assets/images/bonfire-outline.svg
    mealPlan:
      breakfast: true
      lunch: true
      dinner: true
      snacks: true
  evacuation:
    color: 'red'
    opacity: 0.7
    weight: 5
    dashArray: '7, 7'
    startIcon: ../assets/images/medkit-outline.svg
    mealPlan:
      breakfast: false
      lunch: false
      dinner: false
      snacks: false
  zero:
    mealPlan:
      breakfast: true
      lunch: true
      dinner: true
      snacks: true

actualRoute:
  gpx: actual_route/combined.gpx
trip:
  - gpx: planned_route/Jeageloaivi_ele.gpx
    name: Day 1
    startIcon: ../assets/images/circle-play-regular.svg
    mealPlan:
      breakfast: false
      lunch: true
      dinner: true
      snacks: true
    description: >
      Lähdemme hotelli Guossilta kohti Sulaojaa joko taksilla tai bussilla.
      Karigasniementieltä lähdemme kävelemään etelään hiekkakuopalle johtavaa tietä.
      Tieltä jatkamme kartassa näkyvää uraa yli Karigasjoen ja kohti tunturiylänköä.
      Yöpaikkaa etsimme jostain Vudnjosjohkan ja Jaegeloaijávrin tuntumasta.
  - gpx: planned_route/Stuorravzi_ele.gpx
    name: Day 2
    description: >
      Kierrämme Duolba Jeageloaivin länsipuolelta, päätyen karttaan merkitylle uralle.
      Seuraamme uraa, mutta ennen Stuorrávžia käännymme ylängöllä kohti itää, ylittäen Stuorrávžin kohdasta missä poroaita ja ura jatkuvat etelään.
      Yövymme todennäköisesti Stuorraskáidilla, jonkin Rátnojohkaan laskevan uoman läheisyydessä.
  - gpx: planned_route/Stuorraskaidi_ele.gpx
    name: Day 3
    description: >
      Seuraamme uraa ja ylitämme Rátnojohkan, Stuorroaivin ja Čeavrájohkan alkulähteet.
      Tästä länteen Čeavrájohoaivin takainen poroerotusaita isoine mönkijäurinee on mahdollinen evakuoitumisereitti.
      Ylitämme Urroaivin ja Kiellajoen. Saatamme yöpyä jo jossain Kiellajoen läheisyydessä.
      Uran ja Kiellajoen risteyksestä, Piekanaäytsin ja Soarvegielaksen pohjoispuolelta kohti Peltoaivia menee meidän lyhennetty reittimme. Tätä reittiä käytämme mikäli sille on jostain syystä tarvertta.
      Ötökkätilanteen niin vaatiessa, nousemme korkeammalle tästä uran ja Kiellajoen risteyksestä, etsien virtaavaa vettä ja yövymme siinä.
  - gpx: planned_route/Urroaivi_kuarvi_ele.gpx
    name: Day 4
    description: >
      Jatkamme uraa läpi Piekanaäytsin kohti Kuárvikozzâa. Sään salliessa huiputamme Kuárvikozzân.
      Kuárvikozzân jälkeen käännymme koiliseen kohti Peltojärven eteläistä hiekkarantaa.
      Olemme varanneet matkalle yhden varapäivän, saatamme yöpyä jossain jo ennen Peltojärveä jos varapäivää ei ole vielä käytetty.
    alternatives:
    - gpx: planned_route/Alt_ele.gpx
      name: Alt route for leg 4, skips leg 5 too
      skips: [5]
      description: >
        Lyhennetty reitti jos sitä tarvitaan.
  - gpx: planned_route/Peltoj_rvi_ele.gpx
    name: Day 5
    description: >
      Peltojärven rannoilta lähdemme nousemaan Peltoaiville.
      Kuljemme tunturissa ja yövymme todennäköisesti nimettömän järven (350.5 mpy) rannalla, Soavveljávrrečopman lounaispuolella.
  - gpx: planned_route/Peltoaivi_ele.gpx
    name: Day 6
    endIcon: ../assets/images/flag-checkered-solid.svg
    mealPlan:
      breakfast: true
      lunch: true
      dinner: false
      snacks: true
    description: >
      Laskeudumme leiripaikasta Peltojoen länsipuolelle. Seuraamme joen viereistä uraa Muotkanruoktuun.

evacuation:
  - gpx: planned_route/Evac_ele.gpx

photo_info:
  cameraOffset:
    realClock: 13.09
    cameraClock: 14.02
    substrackt: "53m"

travel_info:
  to:
    - transportation:
        type: train
        from: JY
        to: TPE
        outboundDate: "2025-07-02"
        outboundTime: 19:15:00.000+03:00
        url: https://www.vr.fi/kertalippu-menomatkan-hakutulokset?from=JY&to=TPE&passengers[0][key]=df74ac8a-7082-44ab-abef-de30c6c1ee4a&passengers[0][type]=ADULT&passengers[1][key]=1f8b6f3e-f33c-4168-8b5b-a685a46f3921&passengers[1][type]=ADULT&outboundDate=2025-07-02
    - transportation:
        type: train
        from: TPE
        to: ROI
        outboundDate: "2025-07-02"
        outboundTime: 23:09:00.000+03:00
        url: https://www.vr.fi/kertalippu-menomatkan-hakutulokset?from=TPE&to=ROI&passengers[0][key]=78b27270-54af-41ef-922b-9ebea4a5f075&passengers[0][type]=ADULT&passengers[1][key]=30d94a33-448c-49be-ab5b-dc50bdc44427&passengers[1][type]=ADULT&outboundDate=2025-07-02&filters[0]=BED_CABIN
    - transportation:
        type: bus
        from: p472
        to: s12140
        outboundDate: "2025-07-03"
        outboundTime: 11:45
        url: https://liput.matkahuolto.fi/connectionlist?lang=fi&departurePlaceId=p472&arrivalPlaceId=s12140&departureDate=2025-07-03#breadcrumb
    - accommodation:
        name: Hotel Guossi Karigasniemi
        url: https://guossi.com/
        checkInDate: "2025-07-03"
        checkOutDate: "2025-07-04"
        checkInTime: 15:00
        checkOutTime: 12:00
  from:
    - accommodation:
        name: Muotkan Ruoktu
        url: https://www.muotkanruoktu.fi/
        checkInDate: "2025-07-10"
        checkOutDate: "2025-07-11"
        checkInTime: 15:00
        checkOutTime: 12:00
    - transportation:
        type: bus
        from: s1971 # Muotkan Ruoktu
        to: p472 # ROI
        outboundDate: "2025-07-11"
        outboundTime: 12:00
        url: https://liput.matkahuolto.fi/connectionlist?lang=fi&departurePlaceId=s1971&arrivalPlaceId=p472&departureDate=2025-07-11#breadcrumb
    - transportation:
        type: train
        from: ROI
        to: HKI
        outboundDate: "2025-07-11"
        outboundTime: 21:00:00.000+03:00
        url: https://www.vr.fi/kertalippu-menomatkan-hakutulokset?from=ROI&to=HKI&passengers[0][key]=a2b8f1d4-3c7e-4a9b-bc6f-0d1e2f3b5a6b&passengers[0][type]=ADULT&passengers[1][key]=a2b8f1d4-3c7e-4a9b-bc6f-0d1e2f3b5a6b&passengers[1][type]=ADULT&outboundDate=2025-07-11
    - transportation:
        type: train
        from: HKI
        to: JY
        outboundDate: "2025-07-12"
        outboundTime: 10:00:00.000+03:00
        url: https://www.vr.fi/kertalippu-menomatkan-hakutulokset?from=HKI&to=JY&passengers[0][key]=2c768f69-7bc3-4a2e-9498-21bccdf959c7&passengers[0][type]=ADULT&passengers[1][key]=2d624db3-bc45-42cd-88d6-a32f314f78f5&passengers[1][type]=ADULT&outboundDate=2025-07-12