heading: Sarek 2025 - TrailTreader

defaults:
  numberOfZeroDays: 1
  tileLayer: Lantmäteriet
  availableTileLayers:
    - "Esri World Imagery"
    - "OpenTopoMap"
    - "OpenStreetMap"
    - "Lantmäteriet"
  walkingSpeed: 3
  trip:
    color: 'black'
    opacity: 0.7
    weight: 7
    endIcon: ../assets/images/bonfire-outline.svg
    mealPlan:
      breakfast: true
      lunch: true
      dinner: true
      snacks: true
  alternatives:
    color: 'blue'
    opacity: 0.7
    weight: 5
    dashArray: '7, 7'
    endIcon: ../assets/images/bonfire-outline.svg
    mealPlan:
      breakfast: true
      lunch: true
      dinner: true
      snacks: true
  evacuation:
    color: 'red'
    opacity: 0.7
    weight: 5
    dashArray: '7, 7'
    startIcon: ../assets/images/medkit-outline.svg
    mealPlan:
      breakfast: false
      lunch: false
      dinner: false
      snacks: false
  zero:
    mealPlan:
      breakfast: true
      lunch: true
      dinner: true
      snacks: true      

trip:
  - gpx: planned_route/day1_ele.gpx
    startIcon: ../assets/images/circle-play-regular.svg
    mealPlan:
      breakfast: false
      lunch: true # Lunch on the road or at Ritsem?
      dinner: true
      snacks: true
  - gpx: planned_route/day2_ele.gpx
  - gpx: planned_route/day3_ele.gpx
  - gpx: planned_route/day4_ele.gpx
    alternatives:
    - gpx: planned_route/day4_alt_ele.gpx
      name: Alt route for leg 4
  - gpx: planned_route/day5_ele.gpx
  - gpx: planned_route/day6_ele.gpx
  - gpx: planned_route/day7_ele.gpx
    endIcon: ../assets/images/flag-checkered-solid.svg
    mealPlan:
      breakfast: true
      lunch: true
      dinner: false # Dinner on the road or at Suorva?
      snacks: true

travel_info:
  to:
    - transportation:
        type: car-pool
        from: Jyväskylä
        to: Gällivare
        outboundDate: "2025-07-18"
        outboundTime: 10:00
    - accommodation:
        name: Scandic Gällivare
        url: https://www.scandichotels.com/fi/hotellit/scandic-gallivare
        checkInDate: "2025-07-18"
        checkOutDate: "2025-07-19"
        checkInTime: 15:00
        checkOutTime: 08:00
    - transportation:
        type: car-pool
        from: Gällivare
        to: Suorva
        outboundDate: "2025-07-19"
        outboundTime: 09:00
    - transportation:
        type: bus
        from: Suorva
        to: Ritsem
        outboundDate: "2025-07-19"
        outboundTime: 11:30
    - transportation:
        type: boat
        from: Ritsem
        to: Akkajaure
        outboundDate: "2025-07-19"
        outboundTime: 11:00
  from:
    - transportation:
        type: car-pool
        from: Suorva
        to: Gällivare
        outboundDate: "2025-07-26"
        outboundTime: 15:00
    - accommodation:
        name: Scandic Gällivare
        url: https://www.scandichotels.com/fi/hotellit/scandic-gallivare
        checkInDate: "2025-07-26"
        checkOutDate: "2025-07-27"
        checkInTime: 15:00
        checkOutTime: 08:00
    - transportation:
        type: car-pool
        from: Gällivare
        to: Jyväskylä
        outboundDate: "2025-07-27"
        outboundTime: 09:00

photo_info:
  cameraOffset:
    realClock: 13.09
    cameraClock: 14.02
    substrackt: "53m"