defaults:
  tileLayer: Lantmäteriet
  walkingSpeed: 3
  trip:
    color: 'black'
    opacity: 0.7
    weight: 7
    endIcon: /assets/images/bonfire-outline.svg
    mealPlan:
      breakfast: true
      lunch: true
      dinner: true
      snacks: true
  alternatives:
    color: 'blue'
    opacity: 0.7
    weight: 5
    dashArray: '7, 7'
    endIcon: /assets/images/bonfire-outline.svg
    mealPlan:
      breakfast: true
      lunch: true
      dinner: true
      snacks: true
  evacuation:
    color: 'red'
    opacity: 0.7
    weight: 5
    dashArray: '7, 7'
    startIcon: /assets/images/medkit-outline.svg
    mealPlan:
      breakfast: false
      lunch: false
      dinner: false
      snacks: false

trip:
  - gpx: planned_route/day1_ele.gpx
    startIcon: /assets/images/circle-play-regular.svg
    mealPlan:
      breakfast: false
      lunch: true
      dinner: true
      snacks: true
  - gpx: planned_route/day2_ele.gpx
  - gpx: planned_route/day3_ele.gpx
    alternatives:
    - gpx: planned_route/day3_alt.gpx
      name: alternative route 1 for leg 3
  - gpx: planned_route/day4_ele.gpx
  - gpx: planned_route/day5_ele.gpx
  - gpx: planned_route/day6_ele.gpx
    endIcon: /assets/images/flag-checkered-solid.svg
    mealPlan:
      breakfast: true
      lunch: true
      dinner: false
      snacks: true

photo_info:
  cameraOffset:
    realClock: 13.09
    cameraClock: 14.02
    substrackt: "53m"